<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Modal_AssignCustomer</name>
   <tag></tag>
   <elementGuidId>eb8ee134-a0f0-484c-a898-415a2957da69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tst_userProfiles_customers_addAssignments</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
