<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>banner_NotificationSuccess</name>
   <tag></tag>
   <elementGuidId>fe4e63ca-38be-4dec-91ef-7ae412d09bc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tst_notification_success</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
