<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Customers</name>
   <tag></tag>
   <elementGuidId>8482a04a-cc79-449e-bd29-50a7a77dc6f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fingerTabs_2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
