<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ActivateAccount</name>
   <tag></tag>
   <elementGuidId>e0570bb2-5623-4c4c-a831-807e38540c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tst_resetPasswordPage_submit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
