<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NewPassword</name>
   <tag></tag>
   <elementGuidId>277b5e88-9b0e-4567-b0bd-890d114bc00a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ResetPasswordInfo_Password</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
