<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConfirmNewPassword</name>
   <tag></tag>
   <elementGuidId>81eb721c-9104-4f27-94da-70f514eb7029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ResetPasswordInfo_ConfirmPassword</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
