<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sideBar_administration</name>
   <tag></tag>
   <elementGuidId>7c6d2613-b42b-4a84-9887-fa95e5a206d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tst_sidebar_Administration</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
